"""Captured API payloads from a real PowerMaster 360R, redacted.

Using real shapes rather than hand-written stubs is what caught the
integer-vs-string unique_id asymmetry and the empty-traits-when-offline
behaviour.
"""

from __future__ import annotations

from typing import Any

STATUS: dict[str, Any] = {
    "connected": True,
    "connected_status": {
        "bba": {"is_connected": True, "state": "online"},
        "gprs": {"is_connected": False, "state": None},
    },
    "discovery": {"completed": True, "stages": 11, "in_queue": 0, "triggered": None},
    "partitions": [{"id": -1, "state": "DISARM", "status": "", "ready": True, "options": []}],
    "rssi": {"level": "", "network": ""},
}

PANEL_INFO: dict[str, Any] = {
    "serial": "1D0B0A",
    "model": "PowerMaster 360R",
    "manufacturer": "Visonic",
    "current_user": "master_user",
    "state_sets": {
        "all": [
            {
                "name": "AWAY",
                "settable": True,
                "options": ["NOENTRY"],
                "statuses": ["EXIT"],
                "transitions": ["DISARM", "HOME"],
            },
            {
                "name": "HOME",
                "settable": True,
                "options": ["NOENTRY"],
                "statuses": ["EXIT"],
                "transitions": ["DISARM", "AWAY"],
            },
            {
                "name": "DISARM",
                "settable": True,
                "options": [],
                "statuses": [],
                "transitions": ["DISARM", "AWAY", "HOME"],
            },
            {
                "name": "ENTRY_DELAY",
                "settable": False,
                "options": [],
                "statuses": [],
                "transitions": ["DISARM"],
            },
            {
                "name": "PROGRAMMING",
                "settable": False,
                "options": [],
                "statuses": [],
                "transitions": [],
            },
        ]
    },
    "partitions": [
        {"id": -1, "active": True, "exit_delay_time": 30, "state_set": "all", "name": "ALL"}
    ],
    "bypass_mode": "manual_bypass",
    "local_wakeup_needed": False,
    "remote_switch_to_programming_mode_requires_user_acceptance": True,
    "features": {
        "video_on_demand": True,
        "alerts": True,
        "enabling_siren": True,
        "disabling_siren": True,
        "wi_fi_connection": True,
        "set_date_time": True,
        "outputs_setup": True,
    },
}

DEVICES: list[dict[str, Any]] = [
    {
        "id": 828774,
        "enrollment_id": None,
        "device_number": 1,
        "device_type": "POWER_LINK",
        "zone_type": None,
        "subtype": "POWER_LINK",
        "preenroll": False,
        "warnings": None,
        "partitions": [1],
        "traits": {},
        "name": "",
        "removable": False,
        "renamable": False,
    },
    {
        "id": 828775,
        "enrollment_id": None,
        "device_number": 1,
        "device_type": "CONTROL_PANEL",
        "zone_type": None,
        "subtype": "VISONIC_PANEL",
        "preenroll": False,
        "warnings": None,
        "partitions": [1],
        "traits": {},
        "name": "",
        "removable": False,
        "renamable": False,
    },
    {
        "id": 828776,
        "enrollment_id": "120-0918",
        "device_number": 1,
        "device_type": "ZONE",
        "zone_type": "HOME_DELAY",
        "subtype": "MOTION",
        "preenroll": False,
        "warnings": None,
        "partitions": [1],
        "traits": {
            "rssi": {
                "average": "strong",
                "current": "strong",
                "channel": 21,
                "repeater": None,
                "last_updated": "2024-11-10 08:52:08",
            },
            "location": {"name": "Living room"},
            "bypass": {"enabled": False},
            "soak": {"enabled": False},
            "rarely_used": {"enabled": False},
            "is_linkable": {"enabled": True},
        },
        "name": "",
        "removable": True,
        "renamable": True,
    },
    {
        "id": 828777,
        "enrollment_id": "104-5058",
        "device_number": 2,
        "device_type": "ZONE",
        "zone_type": "DELAY_1",
        "subtype": "CONTACT_V",
        "preenroll": False,
        "warnings": None,
        "partitions": [1],
        "traits": {
            "rssi": {
                "average": "strong",
                "current": "strong",
                "channel": 4,
                "repeater": None,
                "last_updated": "2024-11-10 08:52:08",
            },
            "location": {"name": "Front door"},
            "bypass": {"enabled": False},
            "soak": {"enabled": False},
            "rarely_used": {"enabled": False},
            "is_linkable": {"enabled": True},
        },
        "name": "",
        "removable": True,
        "renamable": True,
    },
    {
        "id": 828778,
        "enrollment_id": "120-1823",
        "device_number": 3,
        "device_type": "ZONE",
        "zone_type": "INTERIOR",
        "subtype": "MOTION",
        "preenroll": False,
        "warnings": None,
        "partitions": [1],
        "traits": {
            "rssi": {
                "average": "strong",
                "current": "strong",
                "channel": 21,
                "repeater": None,
                "last_updated": "2024-11-10 08:52:08",
            },
            "location": {"name": "Upstairs"},
            "bypass": {"enabled": False},
            "soak": {"enabled": False},
            "rarely_used": {"enabled": False},
            "is_linkable": {"enabled": True},
        },
        "name": "",
        "removable": True,
        "renamable": True,
    },
    {
        "id": 828779,
        "enrollment_id": "371-3367",
        "device_number": 1,
        "device_type": "WIRELESS_COMMANDER",
        "zone_type": None,
        "subtype": "PROXIMITY_KEYPAD",
        "preenroll": False,
        "warnings": None,
        "partitions": [1],
        "traits": {
            "rssi": {
                "average": "strong",
                "current": "strong",
                "channel": 17,
                "repeater": None,
                "last_updated": "2024-11-10 08:52:08",
            }
        },
        "name": "",
        "removable": True,
        "renamable": True,
    },
    {
        "id": 828780,
        "enrollment_id": "412-3709",
        "device_number": 1,
        "device_type": "WL_SIREN",
        "zone_type": None,
        "subtype": "SOUNDER",
        "preenroll": False,
        "warnings": None,
        "partitions": [1],
        "traits": {
            "rssi": {
                "average": "strong",
                "current": "strong",
                "channel": 4,
                "repeater": None,
                "last_updated": "2024-11-10 08:52:08",
            }
        },
        "name": "",
        "removable": True,
        "renamable": True,
    },
    {
        "id": 6148585,
        "enrollment_id": "104-2984",
        "device_number": 4,
        "device_type": "ZONE",
        "zone_type": "INTERIOR_DELAY",
        "subtype": "CONTACT_V",
        "preenroll": False,
        "warnings": None,
        "partitions": [1],
        "traits": {
            "rssi": {
                "average": "strong",
                "current": "strong",
                "channel": 8,
                "repeater": None,
                "last_updated": "2024-11-10 08:52:08",
            },
            "location": {"name": "Utility room"},
            "bypass": {"enabled": False},
            "soak": {"enabled": False},
            "rarely_used": {"enabled": False},
            "is_linkable": {"enabled": True},
        },
        "name": "",
        "removable": True,
        "renamable": True,
    },
    {
        "id": 6148586,
        "enrollment_id": "120-2904",
        "device_number": 5,
        "device_type": "ZONE",
        "zone_type": "HOME_DELAY",
        "subtype": "MOTION",
        "preenroll": False,
        "warnings": [
            {"type": "INACTIVE", "severity": "TROUBLE", "in_memory": False},
            {"type": "1_WAY", "severity": "TROUBLE", "in_memory": False},
        ],
        "partitions": [1],
        "traits": {
            "rssi": {
                "average": "strong",
                "current": "strong",
                "channel": 8,
                "repeater": None,
                "last_updated": "2024-11-10 08:52:08",
            },
            "location": {"name": "Kitchen"},
            "bypass": {"enabled": False},
            "soak": {"enabled": False},
            "rarely_used": {"enabled": False},
            "is_linkable": {"enabled": True},
        },
        "name": "",
        "removable": True,
        "renamable": True,
    },
    {
        "id": 6149210,
        "enrollment_id": "120-3045",
        "device_number": 6,
        "device_type": "ZONE",
        "zone_type": "HOME_DELAY",
        "subtype": "MOTION",
        "preenroll": False,
        "warnings": None,
        "partitions": [1],
        "traits": {
            "rssi": {
                "average": "strong",
                "current": "strong",
                "channel": 8,
                "repeater": None,
                "last_updated": "2024-11-10 08:52:08",
            },
            "location": {"name": "Office"},
            "bypass": {"enabled": False},
            "soak": {"enabled": False},
            "rarely_used": {"enabled": False},
            "is_linkable": {"enabled": True},
        },
        "name": "",
        "removable": True,
        "renamable": True,
    },
    {
        "id": 6151684,
        "enrollment_id": "120-3114",
        "device_number": 7,
        "device_type": "ZONE",
        "zone_type": "INTERIOR",
        "subtype": "MOTION",
        "preenroll": False,
        "warnings": None,
        "partitions": [1],
        "traits": {
            "rssi": {
                "average": "strong",
                "current": "strong",
                "channel": 4,
                "repeater": None,
                "last_updated": "2024-11-10 08:52:08",
            },
            "location": {"name": "Master Bdrm"},
            "bypass": {"enabled": False},
            "soak": {"enabled": False},
            "rarely_used": {"enabled": False},
            "is_linkable": {"enabled": True},
        },
        "name": "Master Bedroom",
        "removable": True,
        "renamable": True,
    },
    {
        "id": 6152435,
        "enrollment_id": "120-7837",
        "device_number": 8,
        "device_type": "ZONE",
        "zone_type": "INTERIOR",
        "subtype": "MOTION",
        "preenroll": False,
        "warnings": None,
        "partitions": [1],
        "traits": {
            "rssi": {
                "average": "strong",
                "current": "strong",
                "channel": 21,
                "repeater": None,
                "last_updated": "2024-11-10 08:52:08",
            },
            "location": {"name": "Bedroom"},
            "bypass": {"enabled": False},
            "soak": {"enabled": False},
            "rarely_used": {"enabled": False},
            "is_linkable": {"enabled": True},
        },
        "name": "Bedroom 4",
        "removable": True,
        "renamable": True,
    },
    {
        "id": 121983908,
        "enrollment_id": "120-5577",
        "device_number": 9,
        "device_type": "ZONE",
        "zone_type": "INTERIOR_DELAY",
        "subtype": "MOTION",
        "preenroll": False,
        "warnings": None,
        "partitions": [1],
        "traits": {
            "rssi": {
                "average": "strong",
                "current": "strong",
                "channel": 4,
                "repeater": None,
                "last_updated": "2024-11-10 08:52:08",
            },
            "location": {"name": "Garage"},
            "bypass": {"enabled": False},
            "soak": {"enabled": False},
            "rarely_used": {"enabled": False},
            "is_linkable": {"enabled": True},
        },
        "name": "",
        "removable": True,
        "renamable": True,
    },
]

TROUBLES: list[dict[str, Any]] = [
    {
        "device_type": "ZONE",
        "zone_type": "HOME_DELAY",
        "zone": 5,
        "location": "Kitchen",
        "trouble_type": "INACTIVE",
        "partitions": [1],
        "zone_name": "",
    },
    {
        "device_type": "ZONE",
        "zone_type": "HOME_DELAY",
        "zone": 5,
        "location": "Kitchen",
        "trouble_type": "1_WAY",
        "partitions": [1],
        "zone_name": "",
    },
]

ALERTS: list[dict[str, Any]] = []

ALARMS: list[dict[str, Any]] = []

EVENTS: list[dict[str, Any]] = [
    {
        "event": 280125392,
        "type_id": 173,
        "label": "DISARM",
        "description": "Disarm after alarm",
        "appointment": "Control Panel",
        "datetime": "2026-08-03 20:14:31",
        "video": False,
        "device_type": "CONTROL_PANEL",
        "zone": 0,
        "zone_name": "",
        "partitions": [1],
    }
]

FEATURE_SET: dict[str, Any] = {
    "events": {"is_enabled": True},
    "datetime": {"is_enabled": True, "supported_timezones": None},
    "partitions": {
        "is_enabled": False,
        "is_labels_enabled": False,
        "is_labels_editable": True,
        "max_partitions": 3,
    },
    "sirens": {"can_enable": True, "can_disable": True},
    "devices": {
        "is_enabled": True,
        "is_enrollable": True,
        "devices": [
            {
                "enrollment_prefix": "300",
                "name": "BASIC_KEYFOB",
                "enroll": True,
                "removing": True,
                "partitions_required": False,
                "users_required": False,
                "is_zone_type_applicable": False,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "301",
                "name": "KEYFOB_ARM_LED",
                "enroll": True,
                "removing": True,
                "partitions_required": False,
                "users_required": False,
                "is_zone_type_applicable": False,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "305",
                "name": "DSC_KEYFOB_1",
                "enroll": True,
                "removing": True,
                "partitions_required": False,
                "users_required": False,
                "is_zone_type_applicable": False,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "306",
                "name": "DSC_KEYFOB_2",
                "enroll": True,
                "removing": True,
                "partitions_required": False,
                "users_required": False,
                "is_zone_type_applicable": False,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "073",
                "name": "PGM_ON_ZONE",
                "enroll": True,
                "removing": True,
                "partitions_required": False,
                "users_required": False,
                "is_zone_type_applicable": False,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "322",
                "name": "TWO_BUTTON",
                "enroll": True,
                "removing": True,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": False,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "",
                "name": "VISONIC_PANEL",
                "enroll": False,
                "removing": False,
                "partitions_required": False,
                "users_required": False,
                "is_zone_type_applicable": False,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "120",
                "name": "MOTION",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": True,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "122",
                "name": "CURTAIN",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": True,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "140",
                "name": "MOTION_CAMERA",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": True,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "160",
                "name": "GLASS_BREAK",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": True,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "123",
                "name": "MOTION_V_ANTIMASK",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": True,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "150",
                "name": "MOTION_DUAL",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": True,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "130",
                "name": "MOTION_OUTDOOR",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": True,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "142",
                "name": "MOTION_OUTDOOR_CAMERA",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": True,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "161",
                "name": "GLASS_BREAK_SMART",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": True,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "126",
                "name": "FLAT_PIR_SMART",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": True,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "200",
                "name": "SMOKE",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": True,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "201",
                "name": "SMOKE_HEAT",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": True,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "230",
                "name": "GAS",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": True,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "220",
                "name": "CO",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": True,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "240",
                "name": "FLOOD",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": True,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "250",
                "name": "TEMPERATURE",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": True,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "241",
                "name": "FLOOD_PROBE",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": True,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "100",
                "name": "CONTACT",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": True,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "101",
                "name": "CONTACT_AUX",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": True,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "104",
                "name": "CONTACT_V",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": True,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "105",
                "name": "CONTACT_IOS",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": True,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "106",
                "name": "CONTACT_4_IN",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": True,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "171",
                "name": "SHOCK_AUX",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": True,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "172",
                "name": "SHOCK_CONTACT_G3",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": True,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "170",
                "name": "SHOCK_CONTACT_AUX_ANTIMASK",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": True,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "173",
                "name": "SHOCK_CONTACT_G2",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": True,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "053",
                "name": "HW_ZONE_CONNECTED_TO_WL_EXPANDER_IOV",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": True,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "370",
                "name": "KEYPAD",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": False,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "371",
                "name": "PROXIMITY_KEYPAD",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": False,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "374",
                "name": "LCD_KEYPAD",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": False,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "410",
                "name": "OUTDOOR",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": False,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "400",
                "name": "INDOOR",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": False,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "411",
                "name": "AC_OUTDOOR",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": False,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "412",
                "name": "SOUNDER",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": False,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "",
                "name": "POWER_LINK",
                "enroll": False,
                "removing": False,
                "partitions_required": False,
                "users_required": False,
                "is_zone_type_applicable": False,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "",
                "name": "GENERIC_PROXY_TAG",
                "enroll": False,
                "removing": False,
                "partitions_required": False,
                "users_required": False,
                "is_zone_type_applicable": False,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "320",
                "name": "SINGLE_BUTTON",
                "enroll": False,
                "removing": False,
                "partitions_required": True,
                "users_required": False,
                "is_zone_type_applicable": False,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "430",
                "name": "BASIC_REPEATER",
                "enroll": False,
                "removing": False,
                "partitions_required": False,
                "users_required": False,
                "is_zone_type_applicable": False,
                "is_zone_applicable": True,
            },
            {
                "enrollment_prefix": "",
                "name": "GENERIC_PGM",
                "enroll": False,
                "removing": False,
                "partitions_required": False,
                "users_required": False,
                "is_zone_type_applicable": False,
                "is_zone_applicable": True,
            },
        ],
        "zone_types": [
            "NON_ALARM",
            "EMERGENCY",
            "FLOOD",
            "GAS",
            "DELAY_1",
            "DELAY_2",
            "INTERIOR_FOLLOW",
            "PERIMETER",
            "PERIMETER_FOLLOW",
            "H24_SILENT",
            "H24_AUDIBLE",
            "FIRE",
            "INTERIOR",
            "HOME_DELAY",
            "TEMPERATURE",
            "ARMING_KEY",
            "OUTDOOR",
            "CO",
            "INTERIOR_DELAY",
            "TAMPER",
            "LINE_FAIL",
            "PSU_FAIL",
            "PANIC",
        ],
        "video_on_demand": True,
    },
    "home_automation_devices": {
        "is_enabled": True,
        "enabling": True,
        "disabling": True,
        "toggling": True,
        "setting": True,
    },
    "state": {"is_enabled": True, "can_set": True, "can_get": True},
    "faults": {"is_enabled": True, "has_alarms": True, "has_alerts": True, "has_troubles": True},
    "diagnostic": {"is_enabled": False},
    "wifi": {"is_enabled": True},
    "locations": {"is_enabled": True},
    "user": {
        "editable_features": [
            "UEF_CODE",
            "UEF_ROLE",
            "UEF_PARTITIONS",
            "UEF_LABEL",
            "UEF_CREATE_USER",
            "UEF_REMOVE_USER",
        ],
        "code_length": [4],
    },
    "emergency": {
        "is_enabled": True,
        "is_support_specified_partitions": True,
        "emergency_actions": ["E_FIRE", "E_PANIC", "E_EMERGENCY"],
    },
    "validation_rules": {"rules": {}, "device_label_rules": {}},
    "cameras": {"rtsp": {"is_enabled": True}, "isr": {"is_enabled": False}},
}

USERS: dict[str, Any] = {
    "max_users_count": 48,
    "users": [
        {
            "id": 1,
            "role": "MASTER_USER",
            "name": "Owner",
            "last_name": "",
            "expiration_date": None,
            "email": "redacted@example.com",
            "partitions": [1, 2, 3],
            "editable_features": [
                "UEF_CODE",
                "UEF_ROLE",
                "UEF_PARTITIONS",
                "UEF_LABEL",
                "UEF_CREATE_USER",
                "UEF_REMOVE_USER",
            ],
        },
        {
            "id": 2,
            "role": "USER",
            "name": "User 2",
            "last_name": "",
            "expiration_date": None,
            "email": "redacted@example.com",
            "partitions": [1],
            "editable_features": [
                "UEF_CODE",
                "UEF_ROLE",
                "UEF_PARTITIONS",
                "UEF_LABEL",
                "UEF_CREATE_USER",
                "UEF_REMOVE_USER",
            ],
        },
        {
            "id": 3,
            "role": "USER",
            "name": "User 3",
            "last_name": "",
            "expiration_date": None,
            "email": "redacted@example.com",
            "partitions": [1],
            "editable_features": [
                "UEF_CODE",
                "UEF_ROLE",
                "UEF_PARTITIONS",
                "UEF_LABEL",
                "UEF_CREATE_USER",
                "UEF_REMOVE_USER",
            ],
        },
        {
            "id": 4,
            "role": "USER",
            "name": "User 4",
            "last_name": "",
            "expiration_date": None,
            "email": "redacted@example.com",
            "partitions": [1],
            "editable_features": [
                "UEF_CODE",
                "UEF_ROLE",
                "UEF_PARTITIONS",
                "UEF_LABEL",
                "UEF_CREATE_USER",
                "UEF_REMOVE_USER",
            ],
        },
        {
            "id": 5,
            "role": "USER",
            "name": "User 5",
            "last_name": "",
            "expiration_date": None,
            "email": "redacted@example.com",
            "partitions": [1],
            "editable_features": [
                "UEF_CODE",
                "UEF_ROLE",
                "UEF_PARTITIONS",
                "UEF_LABEL",
                "UEF_CREATE_USER",
                "UEF_REMOVE_USER",
            ],
        },
    ],
    "reserved_ids": [],
}

PANELS: list[dict[str, Any]] = [
    {
        "panel_serial": "1D0B0A",
        "panel_model": "PowerMaster 360R",
        "alias": "Example House",
        "role": "MASTER_USER",
        "type": "POWER_MASTER",
        "customization": {
            "id": 1,
            "name": "Default",
            "is_default": True,
            "created": 0,
            "changed": 1689192872,
            "data": {
                "apptype": "",
                "android": "market://details?id=com.visonic.neo",
                "ios": "itms-apps://itunes.apple.com/app/connectalarm/id1300525077",
                "customization": {
                    "themes": [
                        {
                            "name": "Estoril",
                            "brightness": "light",
                            "colors": {
                                "primary": "#006AFF",
                                "gradient": ["#00539E", "#21329D", "#2A2A9D"],
                            },
                        },
                        {
                            "name": "Azurite",
                            "brightness": "dark",
                            "colors": {
                                "primary": "#00A3FF",
                                "gradient": ["#1A2B3B", "#222133", "#261D2D"],
                            },
                        },
                    ]
                },
            },
        },
    }
]
